### PR TITLE
Added ability to setup proxy for requests to Telegram API

### PR DESCRIPTION
**Pull request by lopatinas**

### CODE REVIEW

**Comment by POPSuL** [comment]
What about SOCKS* proxy support?

**Comment by lopatinas** [comment]
It is supported with CURLOPT_PROXY option:
https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by lopatinas** [comment]
It is possible to set login and password in CURLOPT_PROXY string:

A proxy host string can also include protocol scheme (http://) and embedded user + password.

**Comment by bupy7** [comment]
Like  `http://username:password@100.100.100.100`, is it ?

**Comment by lopatinas** [comment]
Yes, it is

**Pull request merged**
