### PR TITLE
Making the library closer to API standards

### PR DESCRIPTION
**Pull request by riartem**
Added language_code property to User object
Added two parameters $switchPmText, $switchPmParameter to answeInlineQuery

### CODE REVIEW

**Comment by riartem** [comment]
Travis broken. It was no error at my code.

**Comment by iGusev** [comment]
FILE: /home/travis/build/TelegramBot/Api/src/BotApi.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 837 | WARNING | Line exceeds 120 characters; contains 169 characters
----------------------------------------------------------------------

**Comment by riartem** [comment]
Omg, its failed again. Whats wrong now?

**Comment by iGusev** [comment]
https://travis-ci.org/TelegramBot/Api/jobs/265663906

FILE: /home/travis/build/TelegramBot/Api/src/BotApi.php
----------------------------------------------------------------------
FOUND 10 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 837 | ERROR | [x] The first parameter of a multi-line function
     |       |     declaration must be on the line after the opening
     |       |     bracket
 837 | ERROR | [x] Multi-line function declarations must define one
     |       |     parameter per line
 837 | ERROR | [x] Multi-line function declarations must define one
     |       |     parameter per line
 837 | ERROR | [x] Multi-line function declarations must define one
     |       |     parameter per line
 837 | ERROR | [x] Whitespace found at end of line
 838 | ERROR | [x] Multi-line function declaration not indented
     |       |     correctly; expected 8 spaces but found 38
 838 | ERROR | [x] Multi-line function declarations must define one
     |       |     parameter per line
 838 | ERROR | [x] Multi-line function declarations must define one
     |       |     parameter per line
 838 | ERROR | [x] The closing parenthesis of a multi-line function
     |       |     declaration must be on a new line
 839 | ERROR | [x] The closing parenthesis and the opening brace of a
     |       |     multi-line function declaration must be on the
     |       |     same line
----------------------------------------------------------------------

**Comment by YaroslavMolchan** [comment]
@riartem you need check code with [PHP CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) before make pull request, all erorrs confilcts with PSR-2 standarts.

**Comment by riartem** [comment]
Ok, I resolved that requirements

**Comment by riartem** [comment]
Seems like your scrutinizer don't work.
image

**Pull request merged**
